name: CI
on:
  [push, pull_request]
jobs:
  generic-build-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    strategy:
      matrix:
        docker_image: [ ubuntu-18.04, ubuntu-20.04, fedora-30, opensuse-leap, ubuntu-22.04]
        compiler: [gcc, clang]
        exclude:
          - docker_image: ubuntu-22.04
            compiler: clang
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Check out repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          DOCKER_IMAGE: ${{ matrix.docker_image }}
          CC: ${{ matrix.compiler }}
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  coverage-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Check out repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          ENABLE_COVERAGE: true
          DOCKER_IMAGE: ubuntu-18.04
          CC: gcc
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  fuzzing-test:
    runs-on: ubuntu-latest
    if: "!contains(github.ref, 'coverity_scan')"
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Check out repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Launch Action
        uses:
          tpm2-software/ci/runCI@main
        with:
          ENABLE_FUZZING: true
          DOCKER_IMAGE: fedora-30
          CC: clang
          PROJECT_NAME: ${{ github.event.repository.name }}
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
  coverity-test:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'coverity_scan')
    steps:
      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Check out repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0
      - name: Launch Action
        uses:
          tpm2-software/ci/coverityScan@main
        with:
          PROJECT_NAME: ${{ github.event.repository.name }}
          REPO_BRANCH: ${{ github.ref }}
          REPO_NAME: ${{ github.repository }}
          ENABLE_COVERITY: true
          DOCKER_IMAGE: ubuntu-18.04
          CC: gcc
          COVERITY_SCAN_TOKEN: ${{ secrets.COVERITY_SCAN_TOKEN }}
          COVERITY_SUBMISSION_EMAIL: william.c.roberts@gmail.com
      - name: failure
        if: ${{ failure() }}
        run: cat build/test-suite.log || true
